kafka:
  bootstrap.servers: 
  security.protocol: SASL_SSL
  sasl.mechanisms: PLAIN
  sasl.username: 
  sasl.password: 
  session.timeout.ms: 5000
registry:
  url: https://psrc-zw3e6jo.us-west-2.aws.confluent.cloud
  registry_key_name:  
app:
  delta_max_time_in_min: 15  # this is to apply randomly to the event timestamp to create out of order

 