services:
  ollama:
    image: ollama/ollama
    hostname: ollama
    volumes:
      - ./start-ollama.sh:/start-ollama.sh
    container_name: ollama
    entrypoint: ["/usr/bin/bash", "/start-ollama.sh"]
    ports:
      - 11434:11434
  pythonenv:
    image: jbcodeforce/shift-left-utils
    hostname: pythonenv
    container_name: pythonenv
    entrypoint: ["/usr/bin/bash"]
    environment:
      - CONFIG_FILE=/app/config.yaml
      - LLM_MODEL=qwen2.5-coder:32b
      - LLM_BASE_URL=http://ollama:11434
    volumes:
      - ./pipelines/:/app/pipelines
      - ./staging/:/app/staging
      - ./config.yaml:/app/config.yaml
      - ./dbt-src/:/app/dbt-src  # change this one