kafka:
  bootstrap.servers:  <TO_FILL>
app:
  logging: INFO
  accepted_common_products: ['common', 'seeds']
  post_fix_unit_test: _jb
  sql_content_modifier: shift_left.core.utils.table_worker.ReplaceEnvInSqlContent
  translator_to_flink_sql_agent: shift_left.core.utils.spark_sql_code_agent.SparkToFlinkSqlAgent
  dml_naming_convention_modifier: shift_left.core.utils.naming_convention.DmlNameModifier
  compute_pool_naming_convention_modifier: shift_left.core.utils.naming_convention.ComputePoolNameModifier
