[project]
name = "shift_left"
version = "0.1.29"
description = "The shift-left CLI to manage your shift-left project"
authors = [
    {name = "jbcodeforce",email = "jerome.boyer@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "rich>=13.9.4",
    "typer>=0.15.2",
    "click <8.2.0",
    "jinja2==3.1.6",
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "pydantic>=2.6.10",
    "pyyaml>=6.0.2",
    # "pemja>0.4.2",
    # "confluent_flink_table_api_python_plugin>=1.20.48"
    "requests>=2.32.3",
    "pydantic-yaml>=1.4.0",
    "toml>=0.10.2",
    "confluent-kafka>=2.10.0",
    "pytest>=8.3.5",
    "pytz>=2025.2",
    "openai>=1.97.1",

]


[project.scripts]
shift_left = "shift_left.cli:app"

[tool.poetry]
packages = [{include = "shift_left", from = "src"}, {include = "ut", from="tests"}]

[tool.poetry.scripts]
shift_left = "shift_left.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/shift_left", "tests"]

[tool.semantic_release]
assets = []
build_command_env = []
build_command = "uv build ."
version_toml = ["pyproject.toml:project.version:nf"]
version_variables= [ "src/shift_left/cli.py:__version__"]
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "conventional"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
repo_dir = "/Users/jerome/Code/shift_left_utils"
no_git_verify = false
tag_format = "v{version}"

[tool.semantic_release.branches.main]
match = "(main)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
exclude_commit_patterns = [
    '''chore(?:\([^)]*?\))?: .+''',
    '''ci(?:\([^)]*?\))?: .+''',
    '''refactor(?:\([^)]*?\))?: .+''',
    '''style(?:\([^)]*?\))?: .+''',
    '''test(?:\([^)]*?\))?: .+''',
    '''build\((?!deps\): .+)''',
    '''Initial [Cc]ommit.*'''
]
mode = "update"
insertion_flag = "<!-- version list -->"
template_dir = "templates"

[tool.semantic_release.changelog.default_templates]
changelog_file = "../../CHANGELOG.md"
output_format = "md"
mask_initial_release = true

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = false

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "jbcodeforce <jerome.boyer@gmail.com>"

[tool.semantic_release.commit_parser_options]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
other_allowed_tags = ["build", "chore", "ci", "docs", "style", "refactor", "test"]
allowed_tags = ["feat", "fix", "perf", "build", "chore", "ci", "docs", "style", "refactor", "test"]
default_bump_level = 0
parse_squash_commits = true
ignore_merge_commits = true

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
insecure = false

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true

