kafka:
  bootstrap.servers:  <TO_FILL>
  security.protocol: SASL_SSL
  sasl.mechanisms: PLAIN
  sasl.username:  <TO_FILL>
  sasl.password:  <TO_FILL>
  session.timeout.ms: 5000
registry:
  url: https://psrc-zw3e6jo.us-west-2.aws.confluent.cloud
  registry_key_name:   <TO_FILL>
  registry_key_secret:  <TO_FILL>
confluent_cloud:
  base_api: api.confluent.cloud/org/v2
  environment_id:  env-<TO_FILL>
  region:  <TO_FILL>
  provider:  <TO_FILL>
  organization_id: <TO_FILL>
  api_key:  <TO_FILL>
  api_secret:  <TO_FILL>
flink:
  api_key:  <TO_FILL>
  api_secret:  <TO_FILL>
  compute_pool_id: lfcp- <TO_FILL>
  url_scope: private
  catalog_name:  <TO_FILL>
  database_name:  <TO_FILL>
app:
  delta_max_time_in_min: 15  # this is to apply randomly to the event timestamp to create out of order
  report_output_dir: ./reports
  default_PK: __db
  src_table_name_suffix: ""
  src_table_name_prefix: src_
 