name: Build and Publish ibu_backend image to docker
env:
  IMAGE_NAME: shift-left-utils
  IMAGE_TAG: latest
on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]
jobs:
  validate-docker-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Validate docker registry secrets are defined
      id: validate-docker-secrets
      run: |
        echo "Validating docker registry secrets are defined on the repository"

        FAIL=false

        validate_secret(){
          FIELD=$1
          VALUE=$2

          if [ -z "${VALUE}" ]; then
            echo "The secret ${FIELD} needs to be set on this repository."
            FAIL=true
          else
            echo "The secret ${FIELD} is set on this repository."
          fi
        }

        validate_secret DOCKER_USER ${DOCKER_USER}
        validate_secret DOCKER_HUB_TOKEN ${DOCKER_HUB_TOKEN}
        validate_secret DOCKER_REGISTRY ${DOCKER_REGISTRY}
        validate_secret DOCKER_REPOSITORY ${DOCKER_R}
        if [ "${FAIL}" = "true" ]; then
          exit 1
        fi
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        DOCKER_R: ${{ secrets.DOCKER_REPOSITORY }}
  publish_images:
    needs:
      validate-docker-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
      - name: Check out owl core repo
        uses: actions/checkout@v4
        with: 
          repository: jbcodeforce/shift-left-utils
          ref: refs/heads/main
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: build docker image
        run: |
          FULL_IMAGE_NAME="${DOCKER_REG}/${DOCKER_R}/${IMAGE_NAME}"
          docker build  -t ${FULL_IMAGE_NAME}:${IMAGE_TAG}
          docker push ${FULL_IMAGE_NAME}:${IMAGE_TAG}
        env:
          DOCKER_U: ${{ secrets.DOCKER_USER }}
          DOCKER_P: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_REG: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_R: ${{ secrets.DOCKER_REPOSITORY }}


